name: Deploy React project usinng Github CICD

on:
  push: 
    branches:
        - main  # <- Main Branch

defaults:
  run:
    working-directory: react-cicd

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # ubuntu machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

    # Optinal but use when jest code present means test file is present
    #   - name: Run tests
    #     run: npm test

      - name: Build The Project
        run: npm run build

      - name: Deploy to Github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist
