name : My First Wrokflow

on : push

jobs :
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout steps
              uses: actions/checkout@v4

            - name: welcome message
              run : echo "First Github Action Job"

            - name : List files
              run : ls 

            - name : Read File
              run : cat README.md