name: Multiple Jobs 🚦

on: 
   push

jobs:
  build_job:   # <-- Job one 
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON ....RAWR 🔥" >> dragon.txt
    
      - name: Sleep for 30 seconds
        run : sleep 30


  test_job:   # <-- Job Two
    needs: build_job    
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run : sleep 10

      - name: Test file Exists
        run: grep -i "dragon" dragon.txt



  deploy_job:
    needs : [build_job,test_job]   # <-- this way you can  use multiple job for one jobs
    runs-on: ubuntu-latest
    steps:
        - name: Read File
          run : cat dragon.txt
        
        - name: Deploy
          run : echo Deploying sucessfulyy...✅

